#!/usr/bin/env bash
# Installs Nginx with the following configurations:

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing the nginx configuration
sudo nginx -t

sudo service nginx reload
