#!/usr/bin/env bash
# script that configure the HTTP Responds header

redirect_to="server_name _;\n\tadd_header X-Served-By \$hostname;\n"

sed -i "s/server_name _;/$redirect_to/" /etc/nginx/sites-enabled/default

# restart nginx
service nginx restart
