#!/usr/bin/env bash
# debugging nginx (service (init) must say that nginx is not running)


sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# restarting nginx
  service nginx restart

# killing nginx process
  pkill -o nginx
